name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ab0a9732c6464e5bb81efb82a2103c7d98f0946f
    - name: Enable Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@b8276522d77f21bf19d3574e5bc99186a6c7aa6c

    - name: Run clippy
      run: |
        nix develop --command cargo clippy --all-targets --all-features -- -D warnings

    - name: Run build
      run: |
        nix develop --command cargo build --verbose

    - name: Run tests
      run: |
        nix develop --command cargo test --verbose

    - name: Run fmt
      run: |
        nix develop --command cargo fmt --check

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ab0a9732c6464e5bb81efb82a2103c7d98f0946f
    - name: Enable Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@b8276522d77f21bf19d3574e5bc99186a6c7aa6c

    - name: Build Nix package
      run: |
        nix build

  all-required-checks-complete:
    if: ${{ always() }}
    needs: [nix-build, rust]
    runs-on: ubuntu-latest
    steps:
      - uses: G-Research/common-actions/check-required-lite@2b7dc49cb14f3344fbe6019c14a31165e258c059
        with:
          needs-context: ${{ toJSON(needs) }}
